name: Build and Publish

on:
  push:
    branches: [ master, modified ]
    tags:
      - '*'
  pull_request:
    branches: [ master, modified ]
  workflow_dispatch:

env: 
  CODE_COVERAGE_PATH: ./Coverage.xml
  SOLUTION_PATH: ./source/Reloaded.Assembler.sln
  NUPKG_GLOB: ./source/Reloaded.Assembler/bin/Release/*.nupkg
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core SDK (6.0.x)
      uses: actions/setup-dotnet@v3
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 9.0.x
    
    - name: Get Dotnet Info
      run: dotnet --info
      
    - name: Build
      run: dotnet build -c Release "$env:SOLUTION_PATH"
      
    - name: Test
      run: |
           dotnet test $env:SOLUTION_PATH /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="../../$env:CODE_COVERAGE_PATH"
        
    - name: Upload NuGet Package Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: NuGet Packages
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ${{ env.NUPKG_GLOB }}
        
    - name: Upload to NuGet (on Tag)
      env: 
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      if: env.IS_RELEASE == 'true'
      run: |
        $items = Get-ChildItem -Path "./source/*.nupkg" -Recurse
        Foreach ($item in $items)
        {
            Write-Host "Pushing $item"
            dotnet nuget push "$item" -k "$env:NUGET_KEY" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        }
